config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  
  resources :games do
    resources :reviews, only: [:new, :index]
  end
  resources :reviews
  resources :genres
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :user #creator of a game, not another join table
  has_many :reviews
  has_many :users, through: :reviews #users who have reviewed the games

  validates :title, presence: true
  validates :title, uniqueness: true

  #accepts_nested_attributes_for :genre 

  def genre_attributes=(attributes)
    self.genre = Genre.find_or_create_by(attributes) if !attributes['name'].empty?
    self.genre
  end

  def self.order_alph
    order(:title)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games

  validates :name, presence: true, uniqueness: true

  def self.order_alph
    order(:name)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :rating, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than: 11}
  validates :content, presence: true
  validates :game, uniqueness: { scope: :user, message: "Error: You've already reviewed this game!"}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :reviewed_games, through: :reviews, source: :game #see odinproject site for how to use source in models
  has_many :games #these are games that the user created; gives us @user.games

  has_secure_password

  validates :username, uniqueness: true,  presence: true
  validates :email, presence: true

  def self.find_or_create_by_google(auth)
    self.find_or_create_by(username: auth[:info][:email]) do |u| #OR: User.where(email: auth[:info][:email]).first_or_initialize
      u.email = auth[:info][:email]
      u.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def not_logged_in?
    if !logged_in?
      redirect_to login_path, :flash => { :alert => "You must be logged in to view this page!"}
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all 
  end

  def new
    @game = Game.new
    @game.build_genre
  end

  def create
    @game = Game.new(game_params)
    @game.user_id = session[:user_id]

    if @game.save
      redirect_to game_path(@game), :flash => { :notice => "Your game was created!"}
    else
      @game.build_genre # keeps new genre field from disappearing after validation error
      render :action => 'new'
    end
  end

  def show
    if @game = Game.find_by_id(params[:id])
    else
      redirect_to games_path, :flash => { :alert => "That game doesn't exist!"}
    end
  end

  private

  def game_params
    params.require(:game).permit(:title, :genre_id, genre_attributes: [:name])
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :not_logged_in?

  def index
    @genres = Genre.all
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_review, only:[:show, :edit, :update, :destroy]
  before_action :not_logged_in?
  
  def index
    #if it's nested and the id is valid
    if @game = Game.find_by_id(params[:game_id])
      @reviews = @game.reviews
    else
      @reviews = Review.all
    end
  end

  def new
    if @game = Game.find_by_id(params[:game_id])
      @review = @game.reviews.build
    else
      @review = Review.new
    end
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to review_path(@review), :flash => { :notice => "Your review was created!"}
    else
      render :new
    end
  end

  def show
    if @review = Review.find_by_id(params[:id])
    else
      redirect_to reviews_path, :flash => { :alert => "That review doesn't exist!"}
    end
  end

  def edit 
    if current_user.id == @review.user_id
    else 
      redirect_to reviews_path,  :flash => { :alert => "You can only edit your own reviews!"}
    end
  end

  def update
    if @review.update(review_params)
      redirect_to review_path(@review), :flash => { :notice => "Your review was edited!"}
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to user_path(@review.user), :flash => { :notice => "Your review was deleted!"}
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content, :game_id)
  end

  def find_review
    @review = Review.find_by_id(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def welcome
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username]) # better to user find_by b/c you can use a key/value pair/doesn't throw an error
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user),  :flash => { :notice => "Welcome!"}
    else
      flash[:error] = "Unable to log in. Please make sure all fields are filled in correctly!"
      redirect_to login_path
    end
  end

  def omniauth
    @user = User.find_or_create_by_google(auth)

    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  def destroy
    session.delete(:user_id) # use #delete here, #destroy is mainly used for objects
    redirect_to '/'
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new # You get the NilClass error when @user has no value (it's nil) when you first load the form on the new action.
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    not_logged_in?
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end
 
  private

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def navigation
    if logged_in?
      render partial: 'layouts/login_navigation'
    end
  end

  def alert_class(flash_type)
    case flash_type.to_sym
    when :notice
      "alert-success"
    when :alert
      "alert-warning"
    when :error
      "alert-danger"
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def display_header(review)
    if params[:game_id]
        content_tag(:h1, "Add a Review for #{review.game.title}")
    else
      content_tag(:h1, "Create a review")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<div class="title-container">
  <h1>All Games</h1>
</div>

<div class="games" align="center">
  <% @games.each do |game| %>
    <div class="game">
      <div class="thumbnail">
        <div class="caption">
          <strong><%= link_to game.title, game_path(game) %></strong></li><br>
          Genre: <%= game.genre.name %><br>
          <%= link_to "Review this game!", new_game_review_path(game) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<div class="title-container">
  <h1>Add a New Game to Review!</h1>
</div>

<%= render partial: 'layouts/errors', locals: {object: @game} %>

<%= form_for(@game) do |f| %>
  <div class="form-group" style="max-width:400px">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <p> Choose an existing genre for this game: </p>
  <%= f.collection_select :genre_id, Genre.order_alph, :id, :name, {include_blank: 'Choose a Genre'}, {class: "form-control"}%>

  <p> Or create a new genre for this game: </p>

  <%= f.fields_for :genre do |genre| %>
    <div class="form-group" style="max-width:400px">
      <%= genre.label :name %>
      <%= genre.text_field :name, class: "form-control" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/games/show.html.erb
<% if  @game.reviews.any?%>
  <h1><%= @game.title %></h1> 
  <h3>Genre: <%= @game.genre.name %></h3> 
  <%= link_to "See all Reviews", game_reviews_path(@game) %>
<% else %>
  <h1>No reviews have been written for <%= @game.title %><h1>
  <h3><%= link_to 'Write the first review!', new_game_review_path(@game) %></h3>
<% end %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<ul>
  <% @genres.each do |genre| %>
    <p><%= genre.name%><p>
  <% end %>
</ul>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger errors">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_login_navigation.html.erb
<ul class="nav navbar-nav navbar-right">
  <li><%= link_to "New Game", new_game_path %></li>
  <li><%= link_to "New Review", new_review_path %></li>
  <li><%= link_to "All Games", games_path %></li>
  <li><%= link_to "All Genres", genres_path %></li>
  <li><%= link_to "All Reviews", reviews_path %></li>
  <li><%= link_to "Log Out", logout_path, method: :delete %></li>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GameReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <% if logged_in? %>
    <header class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
          <%= link_to "Game Review", user_path(current_user), class: "navbar-brand" %>
          </div>
          <div class="nav navbar-nav navbar-right">
            <%= navigation %>
          </div>
        </div>
      </nav>
    </header>
  <% end %>

  <body class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <h4><%= flash[:notice] %></h4>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <h4><%= flash[:alert] %></h4>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <h4><%= flash[:error] %></h4>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @review} %>

<%= form_for(@review) do |f| %>
  <% if params[:game_id] %>
    <%= f.hidden_field :game_id %>
  <% else %>
    <div class="form-group" style="max-width:400px">
      <%= f.label :game_id, "Choose a Game" %>
      <%= f.collection_select :game_id, Game.order_alph, :id, :title, {include_blank: true}, {class: "form-control"} %>
    </div>
  <% end %><br>
  
  <div class="form-group" style="max-width:110px">
    <%= f.label :rating %> out of 10
    <%= f.number_field :rating, min: 0, max: 10, class: "form-control container" %>
  </div>

  <br>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, size: "50x10", class: "form-control" %>
  </div>

  <br>
  <div class="actions">
  <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit This Review!</h1>

<%= render partial: 'form' %>

app/views/reviews/index.html.erb
<div class="title-container">
  <h1>All Reviews</h1>
</div>

<div class="reviews" align="center">
  <% @reviews.each do |review| %>
    <div class="review">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= link_to review.game.title, review_path(review) %></h3>
          <p>Score: <%= review.rating %>/10</p>
          <p>Reviewer: <%= link_to review.user.username, user_path(review.user) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="title-container">
  <%= display_header(@review) %>
</div>

<%= render partial: 'form' %>

app/views/reviews/show.html.erb
<h1><%= @review.game.title %> Review</h1>
<h2>Score: <%= @review.rating %>/10</h2>
<p><%= @review.content %></p>
<p>Written By: <%= @review.user.username %></p>
<div class="actions">
  <%= link_to "Edit Review", edit_review_path(@review), class: "btn btn-primary" if @review.user == current_user%><br><br>
  <%= button_to 'Delete Review', review_path(@review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" if @review.user == current_user %>
</div>

app/views/users/new.html.erb
<h4><%= link_to "Home", "/" %></h4>
<h1>Welcome to Game Review!</h1>
<h3>Sign up!</h3>

<%= render partial: 'layouts/errors', locals: {object: @user}  %>

<%= form_for(@user) do |f| %>
  <div class="form-group" style="max-width:250px">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group" style="max-width:250px">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group" style="max-width:250px">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="actions">
  <%= f.submit "Sign Up", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile!</h1>

<div class="users" align="center">
  <% @user.reviews.each do |review| %>
    <div class="user">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= review.game.title %></h3>
          <p>Score: <%= review.rating %>/10</p>
          <p><%= review.content %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>